QT3 create Test Case tests
Balexer/Qase_Test pull request #7
Opened 2022-02-21 11:53 UTC by Balexer

2022-02-22 05:58 UTC, julsinkevich requested changes

2022-02-22 05:58 UTC, julsinkevich commented on Qase_Test/Src/Pages/Case/CreateTestCasePage.cs
> +        private const string TextPropertySelector =
Одинаковая часть локатора у TextPropertySelector и PropertyButtonSelector  - //label[text()='replace']/../div

2022-02-22 05:58 UTC, julsinkevich commented on Qase_Test/Src/Pages/Case/CreateTestCasePage.cs
> +        private const string PropertyButtonSelector = "//label[text()='replace']/../div";
Используй, пожалуйста, одинаковую стилистику или тип By или string

2022-02-22 05:58 UTC, julsinkevich commented on Qase_Test/Src/Pages/Project/ProjectPage.cs
> +                return false;
Log и сообщение об ошибке

2022-02-22 05:58 UTC, julsinkevich commented on Qase_Test/Src/Pages/Project/ProjectSettingsPage.cs
> +                WebElementActions.GetElement(_deleteProjectButtonSelector).Click();
Log и сообщение об ошибке

2022-02-22 05:58 UTC, julsinkevich commented on Qase_Test/Src/Tests/UiTests/TestCaseTests.cs
> +        [Test]
Реализуй allure, описание - атрибуты аналогичные другим тестам

2022-02-22 05:58 UTC, julsinkevich commented on Qase_Test/Src/Tests/UiTests/TestCaseTests.cs
> +        public void CreateDefaultTestCaseTest()
попробуй использовать атрибут TestCaseSource для объедения теста CreateDefaultTestCaseTest и CreateTestCase в один тест, на разные параметры

2022-02-22 05:58 UTC, julsinkevich commented on Qase_Test/Src/Tests/UiTests/TestCaseTests.cs
> +            LoginSteps = new LoginSteps();
LoginSteps и _user используется в Login/Project/TestCaseTest - может можно это вынести в Base?

2022-02-22 05:58 UTC, julsinkevich commented on Qase_Test/Src/Utils/WebElementActions.cs
> +        public static IWebElement GetElementWithoutWaiters(By locator) =>
немного непонятна логика, при создании LoginTest и ProjectTest - ты везде использовал с ожиданием, здесь уже без.. объясни, пожалуйста

2022-02-22 05:58 UTC, julsinkevich commented on Qase_Test/Src/Tests/UiTests/TestCaseTests.cs
> +            _testCasesSteps.GetTestCase(defaultTestCase).Should().BeEquivalentTo(defaultTestCase);
При создании дефолтного проекта, а лучше назвать "Create a case with required fields" должны заполнятся только поля с *, а уже на этапе BeEquivalentTo идет проверка, что проект у котрого при заполнении только обязаетльных полей, остальные приняли дефолтное значение. То есть открывать dropdown и выбирать значение дефолтное значение - не имеет смысла

2022-02-22 05:58 UTC, julsinkevich commented on Qase_Test/Src/Steps/UiSteps/TestCasesSteps.cs
> +            var tCase = new TestCase()
tCase лучше переименовать.

2022-02-22 05:58 UTC, julsinkevich commented on Qase_Test/Src/Pages/Project/ProjectPage.cs
> +        private const string TextPropertySelector = "//h3[text()='replace']/..//p";
string vs By

2022-02-25 07:11 UTC, ezhukovskaya requested changes

2022-02-25 07:11 UTC, ezhukovskaya commented on Qase_Test/Src/Core/Browser/BrowserSettings.cs
> +    public class BrowserSettings : ReadProperties
remove ReadProperties inheritance. There's no OOP connection between these classes

2022-02-25 07:11 UTC, ezhukovskaya commented on Qase_Test/Src/Core/Browser/BrowserSettings.cs
> +        public static TimeSpan Timeout => TimeSpan.FromSeconds(Convert.ToDouble(Configuration[nameof(Timeout)]));
use double.Parse instead of Convert.ToDouble

2022-02-25 07:11 UTC, ezhukovskaya commented on Qase_Test/Src/Core/UserSettings.cs
> +    public class UserSettings : ReadProperties
remove ReadProperties inheritance. There's no OOP connection between these classes

2022-02-25 07:11 UTC, ezhukovskaya commented on Qase_Test/Src/Pages/Project/ProjectSettingsPage.cs
> +                BaseElement.GetElement(_deleteProjectButtonSelector).Click();
we talked about such cases, you should create instance for Input, Button or Dropdown

2022-02-28 09:28 UTC, ezhukovskaya approved these changes

2022-02-28 09:28 UTC, merged